[package]
name = "stakpak-tui"
version = { workspace = true }
edition = "2024"

[dependencies]
ansi-to-tui = "7.0.0"
chrono = "0.4"
console = "0.15"
crossterm = { workspace = true }
ignore = "0.4.23"
nucleo-matcher = "0.3.1"
open = { workspace = true }
popup-widget = { path = "../libs/popup-widget" }
rand = "0.9"
ratatui = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
stakpak-api = { path = "../libs/api" }
stakpak-shared = { path = "../libs/shared" }
syntect = "5.2.0"
tempfile = { workspace = true }
textwrap = "0.16.2"
tokio = { version = "1.39", features = ["full"] }
unicode-segmentation = "1.12.0"
unicode-width = "0.2.0"
uuid = { workspace = true }

[target.'cfg(unix)'.dependencies]
portable-pty = "0.8"

[lints.clippy]
expect_used = "deny"
unwrap_used = "deny"
