[package]
name = "stakpak-api"
version = { workspace = true }
edition = "2024"
description = "API client library for Stakpak Agent with Anthropic Claude Code and OpenAI support"
readme = "../../README.md"
repository = "https://github.com/kjanat/stakpak"
license = "Apache-2.0"
keywords = ["anthropic", "api", "claude", "client", "openai"]
categories = ["api-bindings", "asynchronous"]

[dependencies]
chrono = { workspace = true }
eventsource-stream = "0.2.3"
futures-util = { workspace = true }
reqwest = { workspace = true }
rmcp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
stakpak-shared = { path = "../../libs/shared" }
url = "2.5.0"
urlencoding = "2.1"
uuid = { workspace = true }
