[package]
name = "stakpak-mcp-server"
version = { workspace = true }
edition = "2024"

[dependencies]
anyhow = { workspace = true }
axum = "0.8.4"
axum-server = { workspace = true }
chrono = { version = "0.4", features = ["serde"] }
fast_html2md = "=0.0.48"
rand = { workspace = true }
reqwest = { workspace = true }
rmcp = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
similar = { workspace = true }
stakpak-api = { path = "../../api" }
stakpak-shared = { path = "../../shared" }
tokio = { workspace = true }
toml = "0.8"
tracing = { workspace = true }
url = "2.5.0"
uuid = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
tempfile = "3.8"

[lints.clippy]
expect_used = "deny"
unwrap_used = "deny"
